springdoc.api-docs.path: /api-docs

setlistFm:
  api:
    baseUrl: https://api.setlist.fm/
    apiKey: ${SETLIST_FM_API_KEY}

spotify:
  api:
    baseUrl: https://api.spotify.com/
    accountsBaseUrl: https://accounts.spotify.com/
    clientId: ${SPOTIFY_CLIENT_ID}
    clientSecret: ${SPOTIFY_CLIENT_SECRET}
  topTracksPlaylistId: 37i9dQZEVXbNG2KDcFcKOF

selenium:
  remoteWebDriverUrl: ${REMOTE_WEB_DRIVER_URL}

